var annotated_dup =
[
    [ "AuxiliarDeExibicaoDeInformacoes", "class_auxiliar_de_exibicao_de_informacoes.html", "class_auxiliar_de_exibicao_de_informacoes" ],
    [ "Controlador", "class_controlador.html", "class_controlador" ],
    [ "ControladorDeDados", "class_controlador_de_dados.html", "class_controlador_de_dados" ],
    [ "ControladorDeOperacoes", "class_controlador_de_operacoes.html", "class_controlador_de_operacoes" ],
    [ "ControladorDeResultados", "class_controlador_de_resultados.html", "class_controlador_de_resultados" ],
    [ "ControladorDoMenuGeral", "class_controlador_do_menu_geral.html", "class_controlador_do_menu_geral" ],
    [ "DecidaControlador", "class_decida_controlador.html", "class_decida_controlador" ],
    [ "DecidaOperacao", "class_decida_operacao.html", "class_decida_operacao" ],
    [ "Evento", "class_evento.html", "class_evento" ],
    [ "Menu", "class_menu.html", "class_menu" ],
    [ "MenuDados", "class_menu_dados.html", "class_menu_dados" ],
    [ "MenuGeral", "class_menu_geral.html", "class_menu_geral" ],
    [ "MenuOperacoes", "class_menu_operacoes.html", "class_menu_operacoes" ],
    [ "MenuResultados", "class_menu_resultados.html", "class_menu_resultados" ],
    [ "Model", "class_model.html", "class_model" ],
    [ "Nota", "class_nota.html", "class_nota" ],
    [ "NotaDAO", "class_nota_d_a_o.html", "class_nota_d_a_o" ],
    [ "NotaService", "class_nota_service.html", "class_nota_service" ],
    [ "Observador", "class_observador.html", "class_observador" ],
    [ "Operacao", "class_operacao.html", "class_operacao" ],
    [ "OperacaoDesdobrar", "class_operacao_desdobrar.html", "class_operacao_desdobrar" ],
    [ "OperacaoSincronizar", "class_operacao_sincronizar.html", "class_operacao_sincronizar" ],
    [ "ProcessadorDeDadosService", "class_processador_de_dados_service.html", "class_processador_de_dados_service" ],
    [ "ProcessadorDeOperacoesService", "class_processador_de_operacoes_service.html", "class_processador_de_operacoes_service" ],
    [ "ProcessadorDeResultadosService", "class_processador_de_resultados_service.html", "class_processador_de_resultados_service" ],
    [ "View", "class_view.html", "class_view" ]
];